CC:=gcc
CXX:=g++
CFLAGS:=-O3 -fPIC
CXXFLAGS:=-O3 -fPIC
INCLUDE:=-I/work1/home/emeneker/local_build/install/libpcap/1.9.1/include
LIBS:=-lpcap

.PHONY=clean

find_macs_and_ips: main.o
	$(CXX) $(CXXFLAGS) main.o -o find_macs_and_ips $(LDFLAGS) $(LIBS)

_ip_extractor.so: C_src/ip_extractor.o
	$(CXX) -o _ip_extractor.so -shared C_src/ip_extractor.o $(LDFLAGS) $(LIBS)

C_src/ip_extractor.o: C_src/ip_extractor.c C_src/ip_extractor.h
	$(CXX) $(CXXFLAGS) -o C_src/ip_extractor.o -c C_src/ip_extractor.c

main.o: main.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDE) -o main.o -c main.cpp

clean:
	rm -f _ip_extractor.so C_src/ip_extractor.o
	rm -f main.o test
