CC:=gcc
CXX:=g++
CFLAGS:=-O3 -fPIC
CXXFLAGS:=-O3 -fPIC
INCLUDE:=-I/work1/home/emeneker/local_build/install/libpcap/1.9.1/include
LIBS:=-lpcap

.PHONY=clean

heuristics: main.o utilities.o iptype.o crc32_x.o ethtype.o find_macs_and_ips utilities_test crc_test macaddresses.o ipaddresses.o
	$(CXX) $(CXXFLAGS) main.o utilities.o iptype.o crc32_x.o ethtype.o macaddresses.o ipaddresses.o ahocorasickbinary.o -o heuristics $(LDFLAGS) $(LIBS)

find_macs_and_ips: find_macs_and_ips.o macaddresses.o ipaddresses.o
	$(CXX) $(CXXFLAGS) find_macs_and_ips.o macaddresses.o ipaddresses.o -o find_macs_and_ips $(LDFLAGS) $(LIBS)

main.o: main.cpp utilities.o iptype.o ethtype.o crc32_x.o macaddresses.o ipaddresses.o ahocorasickbinary.o
	$(CXX) $(CXXFLAGS) $(INCLUDE) -o main.o -c main.cpp

find_macs_and_ips.o: find_macs_and_ips.cpp ipaddresses.o macaddresses.o
	$(CXX) $(CXXFLAGS) $(INCLUDE) -o find_macs_and_ips.o -c find_macs_and_ips.cpp

utilities.o: utilities.cpp utilities.h
	$(CXX) $(CXXFLAGS) $(INCLUDE) -o utilities.o -c utilities.cpp

utilities_test.o: utilities_test.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDE) -o utilities_test.o -c utilities_test.cpp

iptype.o: iptype.cpp iptype.h
	$(CXX) $(CXXFLAGS) $(INCLUDE) -o iptype.o -c iptype.cpp

ethtype.o: ethtype.cpp ethtype.h
	$(CXX) $(CXXFLAGS) $(INCLUDE) -o ethtype.o -c ethtype.cpp

crc32_x.o: crc32_x.cpp crc32_x.h
	$(CXX) $(CXXFLAGS) $(INCLUDE) -o crc32_x.o -c crc32_x.cpp

crc_test.o: crc_test.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDE) -o crc_test.o -c crc_test.cpp

crc_test: crc_test.o crc32_x.o
	$(CXX) $(CXXFLAGS) crc_test.o crc32_x.o -o crc_test $(LDFLAGS) $(LIBS)

macaddresses.o: macaddresses.cpp macaddresses.h
	$(CXX) $(CXXFLAGS) $(INCLUDE) -o macaddresses.o -c macaddresses.cpp

ipaddresses.o: ipaddresses.cpp ipaddresses.h
	$(CXX) $(CXXFLAGS) $(INCLUDE) -o ipaddresses.o -c ipaddresses.cpp

utilities_test: utilities_test.o utilities.o ahocorasickbinary.o
	$(CXX) $(CXXFLAGS) utilities_test.o utilities.o ahocorasickbinary.o -o utilities_test $(LDFLAGS) $(LIBS)

ahocorasickbinary.o: ahocorasickbinary.cpp ahocorasickbinary.h
	$(CXX) $(CXXFLAGS) $(INCLUDE) -o ahocorasickbinary.o -c ahocorasickbinary.cpp

clean:
	rm -f main.o heuristics crc_test utilities.o iptype.o crc32_x.o crc_test.o a.out ethtype.o utilities_test utilities_test.o find_macs_and_ips.o find_macs_and_ips macaddresses.o ipaddresses.o ahocorasickbinary.o
