CC:=gcc
CXX:=g++
CFLAGS:=-O3 -fPIC
CXXFLAGS:=-O3 -fPIC
INCLUDE:=-I/work1/home/emeneker/local_build/install/libpcap/1.9.1/include
LIBS:=-lpcap

.PHONY=clean

heuristics: main.o utilities.o iptype.o crc32_x.o
	$(CXX) $(CXXFLAGS) main.o utilities.o iptype.o crc32_x.o -o heuristics $(LDFLAGS) $(LIBS)

main.o: main.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDE) -o main.o -c main.cpp

utilities.o: utilities.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDE) -o utilities.o -c utilities.cpp

iptype.o: iptype.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDE) -o iptype.o -c iptype.cpp

crc32_x.o: crc32_x.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDE) -o crc32_x.o -c crc32_x.cpp

crc_test.o: crc_test.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDE) -o crc_test.o -c crc_test.cpp

crc_test: crc_test.o crc32_x.o
	$(CXX) $(CXXFLAGS) crc_test.o crc32_x.o -o crc_test $(LDFLAGS) $(LIBS)

clean:
	rm -f main.o heuristics crc_test utilities.o iptype.o crc32_x.o crc_test.o a.out
